// Complete index of every preloadable image asset under assets/used/.
// Cursors are CSS url() strings managed by the browser and are excluded.
// Preview/meta PNGs (_preview*) are never loaded at runtime and are excluded.
//
// Use ALL_ASSETS to preload everything at startup:
//   for (const src of ALL_ASSETS) { const img = new Image(); img.src = src; }

export const ACTOR_ASSETS = [
  'assets/used/actors/poodle-se.png',
  'assets/used/actors/poodle-walk-ne.png',
  'assets/used/actors/poodle-walk-nw.png',
  'assets/used/actors/poodle-walk-se.png',
  'assets/used/actors/poodle-walk-sw.png',
] as const;

export const BUILDING_ASSETS = [
  'assets/used/buildings/animal-farm.png',
  'assets/used/buildings/cart-empty.png',
  'assets/used/buildings/cart-fetching.png',
  'assets/used/buildings/cart-loaded.png',
  'assets/used/buildings/chapel.png',
  'assets/used/buildings/clinic.png',
  'assets/used/buildings/courthouse.png',
  'assets/used/buildings/crop-farm.png',
  'assets/used/buildings/delete.png',
  'assets/used/buildings/dock.png',
  'assets/used/buildings/engineer-station.png',
  'assets/used/buildings/fire-station.png',
  'assets/used/buildings/fishermen-wharf.png',
  'assets/used/buildings/food-processing-workshop.png',
  'assets/used/buildings/grove-farm.png',
  'assets/used/buildings/house-tier-1.png',
  'assets/used/buildings/house-tier-2.png',
  'assets/used/buildings/house-tier-3.png',
  'assets/used/buildings/house-tier-4.png',
  'assets/used/buildings/house-tier-5.png',
  'assets/used/buildings/house-tier-6.png',
  'assets/used/buildings/house.png',
  'assets/used/buildings/marketplace.png',
  'assets/used/buildings/mine-camp.png',
  'assets/used/buildings/police-station.png',
  'assets/used/buildings/road.png',
  'assets/used/buildings/school.png',
  'assets/used/buildings/ship.png',
  'assets/used/buildings/shipyard.png',
  'assets/used/buildings/tavern.png',
  'assets/used/buildings/university-map.png',
  'assets/used/buildings/warehouse-map.png',
  'assets/used/buildings/warehouse.png',
  'assets/used/buildings/well.png',
  'assets/used/buildings/workshop.png',
] as const;

export const COAT_OF_ARMS_ASSETS = [
  'assets/used/coat-of-arms/anrelia.png',
  'assets/used/coat-of-arms/columbia.png',
  'assets/used/coat-of-arms/jinlin.png',
  'assets/used/coat-of-arms/mintaka.png',
  'assets/used/coat-of-arms/solara.png',
] as const;

export const MAP_TILE_ASSETS = [
  // Base terrain fills
  'assets/used/map-tiles/dirt.png',
  'assets/used/map-tiles/grass.png',
  'assets/used/map-tiles/sand.png',
  'assets/used/map-tiles/sea.png',
  // Road auto-tile shapes
  'assets/used/map-tiles/road/corner.png',
  'assets/used/map-tiles/road/cross.png',
  'assets/used/map-tiles/road/end.png',
  'assets/used/map-tiles/road/isolated.png',
  'assets/used/map-tiles/road/straight.png',
  'assets/used/map-tiles/road/tee.png',
  // Terrain surface overlays (dual-grid Wang tiles)
  'assets/used/map-tiles/surfaces/grass/main.png',
  'assets/used/map-tiles/surfaces/grass/alternative-1.png',
  'assets/used/map-tiles/surfaces/rock-grass/main.png',
  'assets/used/map-tiles/surfaces/rock-grass/alternative-1.png',
  'assets/used/map-tiles/surfaces/sand/main.png',
  'assets/used/map-tiles/surfaces/sand/alternative-1.png',
  'assets/used/map-tiles/surfaces/sea/main.png',
  'assets/used/map-tiles/surfaces/sea/alternative-1.png',
  // Terrain blend corners (unused corner-mask/edge helpers excluded)
  'assets/used/map-tiles/blend/dirt-grass/0.png',
  'assets/used/map-tiles/blend/dirt-grass/1.png',
  'assets/used/map-tiles/blend/dirt-grass/2.png',
  'assets/used/map-tiles/blend/dirt-grass/3.png',
  'assets/used/map-tiles/blend/dirt-grass/4.png',
  'assets/used/map-tiles/blend/dirt-grass/5.png',
  'assets/used/map-tiles/blend/dirt-grass/6.png',
  'assets/used/map-tiles/blend/dirt-grass/7.png',
  'assets/used/map-tiles/blend/dirt-grass/8.png',
  'assets/used/map-tiles/blend/dirt-grass/9.png',
  'assets/used/map-tiles/blend/dirt-grass/A.png',
  'assets/used/map-tiles/blend/dirt-grass/B.png',
  'assets/used/map-tiles/blend/dirt-grass/C.png',
  'assets/used/map-tiles/blend/dirt-grass/D.png',
  'assets/used/map-tiles/blend/dirt-grass/E.png',
  'assets/used/map-tiles/blend/dirt-grass/F.png',
  'assets/used/map-tiles/blend/grass-sand/0.png',
  'assets/used/map-tiles/blend/grass-sand/1.png',
  'assets/used/map-tiles/blend/grass-sand/2.png',
  'assets/used/map-tiles/blend/grass-sand/3.png',
  'assets/used/map-tiles/blend/grass-sand/4.png',
  'assets/used/map-tiles/blend/grass-sand/5.png',
  'assets/used/map-tiles/blend/grass-sand/6.png',
  'assets/used/map-tiles/blend/grass-sand/7.png',
  'assets/used/map-tiles/blend/grass-sand/8.png',
  'assets/used/map-tiles/blend/grass-sand/9.png',
  'assets/used/map-tiles/blend/grass-sand/A.png',
  'assets/used/map-tiles/blend/grass-sand/B.png',
  'assets/used/map-tiles/blend/grass-sand/C.png',
  'assets/used/map-tiles/blend/grass-sand/D.png',
  'assets/used/map-tiles/blend/grass-sand/E.png',
  'assets/used/map-tiles/blend/grass-sand/F.png',
  'assets/used/map-tiles/blend/sand-sea/0.png',
  'assets/used/map-tiles/blend/sand-sea/1.png',
  'assets/used/map-tiles/blend/sand-sea/2.png',
  'assets/used/map-tiles/blend/sand-sea/3.png',
  'assets/used/map-tiles/blend/sand-sea/4.png',
  'assets/used/map-tiles/blend/sand-sea/5.png',
  'assets/used/map-tiles/blend/sand-sea/6.png',
  'assets/used/map-tiles/blend/sand-sea/7.png',
  'assets/used/map-tiles/blend/sand-sea/8.png',
  'assets/used/map-tiles/blend/sand-sea/9.png',
  'assets/used/map-tiles/blend/sand-sea/A.png',
  'assets/used/map-tiles/blend/sand-sea/B.png',
  'assets/used/map-tiles/blend/sand-sea/C.png',
  'assets/used/map-tiles/blend/sand-sea/D.png',
  'assets/used/map-tiles/blend/sand-sea/E.png',
  'assets/used/map-tiles/blend/sand-sea/F.png',
] as const;

export const POPULATION_ASSETS = [
  'assets/used/population/busts/artisan-bust-v2-clean-alpha.png',
  'assets/used/population/busts/entrepreneur-bust-v2-clean-alpha.png',
  'assets/used/population/busts/farmer-bust-v2-clean-alpha.png',
  'assets/used/population/busts/magnate-bust-v2-clean-alpha.png',
  'assets/used/population/busts/scholar-bust-v2-clean-alpha.png',
  'assets/used/population/busts/worker-bust-v2-clean-alpha.png',
] as const;

export const RESOURCE_ASSETS = [
  'assets/used/resources/apple.png',
  'assets/used/resources/banana.png',
  'assets/used/resources/berry.png',
  'assets/used/resources/boot.png',
  'assets/used/resources/brandy.png',
  'assets/used/resources/bread.png',
  'assets/used/resources/brick.png',
  'assets/used/resources/cabbage.png',
  'assets/used/resources/candle.png',
  'assets/used/resources/cheese.png',
  'assets/used/resources/chicken.png',
  'assets/used/resources/cider.png',
  'assets/used/resources/cigar.png',
  'assets/used/resources/clam.png',
  'assets/used/resources/clay.png',
  'assets/used/resources/coal.png',
  'assets/used/resources/cocoa.png',
  'assets/used/resources/coin.png',
  'assets/used/resources/concrete.png',
  'assets/used/resources/copper.png',
  'assets/used/resources/corn.png',
  'assets/used/resources/cotton.png',
  'assets/used/resources/cow.png',
  'assets/used/resources/egg.png',
  'assets/used/resources/feather-hat.png',
  'assets/used/resources/fertilizer.png',
  'assets/used/resources/fish.png',
  'assets/used/resources/flour.png',
  'assets/used/resources/fur-coat.png',
  'assets/used/resources/fur.png',
  'assets/used/resources/furniture.png',
  'assets/used/resources/gem.png',
  'assets/used/resources/glass.png',
  'assets/used/resources/gold-ore.png',
  'assets/used/resources/grape.png',
  'assets/used/resources/horse.png',
  'assets/used/resources/iron-ingot.png',
  'assets/used/resources/iron-ore.png',
  'assets/used/resources/ivory.png',
  'assets/used/resources/jam.png',
  'assets/used/resources/jewelry.png',
  'assets/used/resources/lettuce.png',
  'assets/used/resources/marble-statue.png',
  'assets/used/resources/marble.png',
  'assets/used/resources/melon.png',
  'assets/used/resources/milk.png',
  'assets/used/resources/noodle.png',
  'assets/used/resources/olive-oil.png',
  'assets/used/resources/olive.png',
  'assets/used/resources/onion.png',
  'assets/used/resources/orange.png',
  'assets/used/resources/pant.png',
  'assets/used/resources/pig.png',
  'assets/used/resources/pork.png',
  'assets/used/resources/potato.png',
  'assets/used/resources/pottery.png',
  'assets/used/resources/pumpkin.png',
  'assets/used/resources/rice.png',
  'assets/used/resources/rubber.png',
  'assets/used/resources/rum.png',
  'assets/used/resources/salt.png',
  'assets/used/resources/sand.png',
  'assets/used/resources/sausage.png',
  'assets/used/resources/sheep.png',
  'assets/used/resources/shirt.png',
  'assets/used/resources/silk.png',
  'assets/used/resources/slate.png',
  'assets/used/resources/soybean.png',
  'assets/used/resources/steel.png',
  'assets/used/resources/stone-blocks.png',
  'assets/used/resources/stone.png',
  'assets/used/resources/sugar-cane.png',
  'assets/used/resources/tea.png',
  'assets/used/resources/timber.png',
  'assets/used/resources/tobacco.png',
  'assets/used/resources/tofu.png',
  'assets/used/resources/tomato.png',
  'assets/used/resources/tool.png',
  'assets/used/resources/wax.png',
  'assets/used/resources/weapon.png',
  'assets/used/resources/whale-oil.png',
  'assets/used/resources/wheat-sheaf-v3.png',
  'assets/used/resources/window.png',
  'assets/used/resources/wine.png',
  'assets/used/resources/wood.png',
  'assets/used/resources/wool.png',
] as const;

export const TERRAIN_ASSETS = [
  'assets/used/terrain/bush/main.png',
  'assets/used/terrain/bush/alternative-1.png',
  'assets/used/terrain/bush/alternative-2.png',
  'assets/used/terrain/bush/alternative-3.png',
  'assets/used/terrain/bush/alternative-4.png',
  'assets/used/terrain/bush/alternative-5.png',
  'assets/used/terrain/bush/alternative-6.png',
  'assets/used/terrain/bush/alternative-7.png',
  'assets/used/terrain/bush/alternative-8.png',
  'assets/used/terrain/bush/alternative-9.png',
  'assets/used/terrain/bush/alternative-10.png',
  'assets/used/terrain/decoration/main.png',
  'assets/used/terrain/decoration/alternative-1.png',
  'assets/used/terrain/decoration/alternative-2.png',
  'assets/used/terrain/decoration/alternative-3.png',
  'assets/used/terrain/decoration/alternative-4.png',
  'assets/used/terrain/decoration/alternative-5.png',
  'assets/used/terrain/decoration/alternative-6.png',
  'assets/used/terrain/decoration/alternative-7.png',
  'assets/used/terrain/decoration/alternative-8.png',
  'assets/used/terrain/decoration/alternative-9.png',
  'assets/used/terrain/decoration/alternative-11.png',
  'assets/used/terrain/decoration/alternative-12.png',
  'assets/used/terrain/decoration/alternative-15.png',
  'assets/used/terrain/decoration/alternative-16.png',
  'assets/used/terrain/mine/alternative-6.png',
  'assets/used/terrain/rock/main.png',
  'assets/used/terrain/rock/alternative-1.png',
  'assets/used/terrain/rock/alternative-2.png',
  'assets/used/terrain/rock/alternative-3.png',
  'assets/used/terrain/tree/main.png',
  'assets/used/terrain/tree/alternative-1.png',
  'assets/used/terrain/tree/alternative-2.png',
  'assets/used/terrain/tree/alternative-3.png',
  'assets/used/terrain/tree/alternative-4.png',
  'assets/used/terrain/tree/alternative-5.png',
  'assets/used/terrain/tree/alternative-6.png',
  'assets/used/terrain/tree/alternative-7.png',
  'assets/used/terrain/tree/alternative-8.png',
  'assets/used/terrain/tree/alternative-9.png',
  'assets/used/terrain/tree/alternative-10.png',
] as const;

export const UI_ASSETS = [
  'assets/used/ui/button.png',
] as const;

export const ALL_ASSETS: readonly string[] = [
  ...ACTOR_ASSETS,
  ...BUILDING_ASSETS,
  ...COAT_OF_ARMS_ASSETS,
  ...MAP_TILE_ASSETS,
  ...POPULATION_ASSETS,
  ...RESOURCE_ASSETS,
  ...TERRAIN_ASSETS,
  ...UI_ASSETS,
];
