import { Resource } from './types'

// Shared resource icon lookup: a cute PNG when art exists, else an emoji.

const RESOURCE_ICON_BASE = 'assets/resource-icons-cute-64/'
const RESOURCE_ICON_FILES: { [key: string]: string } = {
  [Resource.APPLE]: 'apple.png',
  [Resource.BANANA]: 'banana.png',
  [Resource.BERRY]: 'berry.png',
  [Resource.BRANDY]: 'brandy.png',
  [Resource.BREAD]: 'bread.png',
  [Resource.BRICK]: 'brick.png',
  [Resource.CABBAGE]: 'lettuce.png',
  [Resource.CANDLE]: 'candle.png',
  [Resource.CHEESE]: 'cheese.png',
  [Resource.CIDER]: 'cider.png',
  [Resource.CIGAR]: 'cigar.png',
  [Resource.CLAY]: 'clay.png',
  [Resource.COAL]: 'coal.png',
  [Resource.COCOA]: 'cocoa.png',
  [Resource.CONCRETE]: 'concrete.png',
  [Resource.CORN]: 'corn.png',
  [Resource.COTTON]: 'cotton.png',
  [Resource.EGG]: 'egg-basket-v2.png',
  [Resource.FISH]: 'fish.png',
  [Resource.FLOUR]: 'flour.png',
  [Resource.FUR]: 'fur.png',
  [Resource.GEM]: 'gem.png',
  [Resource.GLASS]: 'glass.png',
  [Resource.GOLD]: 'coin.png',
  [Resource.GRAPE]: 'grape.png',
  [Resource.IRON]: 'iron-ingot.png',
  [Resource.JAM]: 'jam.png',
  [Resource.MELON]: 'melon.png',
  [Resource.MILK]: 'milk.png',
  [Resource.OIL]: 'olive-oil-jug-v3.png',
  [Resource.OLIVE]: 'olive.png',
  [Resource.ORANGE]: 'orange.png',
  [Resource.ONION]: 'onion.png',
  [Resource.FURNITURE]: 'furniture.png',
  [Resource.JEWELRY]: 'jewelry.png',
  [Resource.IRON_ORE]: 'iron-ore.png',
  [Resource.GOLD_ORE]: 'gold-ore.png',
  [Resource.PANT]: 'pant.png',
  [Resource.TIMBER]: 'timber.png',
  [Resource.TOOL]: 'tool.png',
  [Resource.PORK]: 'pig.png',
  [Resource.POTATO]: 'potato.png',
  [Resource.POTTERY]: 'pottery-household-v2.png',
  [Resource.PUMPKIN]: 'pumpkin.png',
  [Resource.SALT]: 'salt.png',
  [Resource.SAND]: 'sand.png',
  [Resource.SAUSAGE]: 'sausage.png',
  [Resource.SLATE]: 'slate.png',
  [Resource.SOYBEAN]: 'soybean.png',
  [Resource.STATUE]: 'marble-statue.png',
  [Resource.STEEL]: 'steel.png',
  [Resource.STONE]: 'stone.png',
  [Resource.SUGAR_CANE]: 'sugar-cane.png',
  [Resource.RICE]: 'rice.png',
  [Resource.RUBBER]: 'rubber.png',
  [Resource.RUM]: 'rum.png',
  [Resource.TOBACCO]: 'tobacco.png',
  [Resource.TOMATO]: 'tomato.png',
  [Resource.WAX]: 'wax.png',
  [Resource.WHEAT]: 'wheat.png',
  [Resource.WINDOW]: 'window.png',
  [Resource.WINE]: 'wine-barrel-v3.png',
  [Resource.WOOD]: 'wood.png',
  [Resource.WOOL]: 'wool.png',
}

const RESOURCE_EMOJI: { [key: string]: string } = {
  [Resource.APPLE]:      '🍎', [Resource.BANANA]:     '🍌', [Resource.BERRY]:      '🍓',
  [Resource.BRANDY]:     '🍾', [Resource.BREAD]:      '🥖', [Resource.BRICK]:      '🧱',
  [Resource.CABBAGE]:    '🥬', [Resource.CANDLE]:     '🕯️', [Resource.CHEESE]:     '🧀',
  [Resource.CIDER]:      '🍺', [Resource.CIGAR]:      '🚬', [Resource.CLAY]:       '🟤',
  [Resource.COAL]:       '⚫', [Resource.COCOA]:      '🍫', [Resource.CONCRETE]:   '🏗️',
  [Resource.CORN]:       '🌽', [Resource.COTTON]:     '🪡', [Resource.EGG]:        '🥚',
  [Resource.FISH]:       '🐟', [Resource.FLOUR]:      '🥣', [Resource.FUR]:        '🦊',
  [Resource.FURNITURE]:  '🪑', [Resource.GEM]:        '💎',
  [Resource.GLASS]:      '🫧', [Resource.GOLD]:       '🪙', [Resource.GOLD_ORE]:   '🏅',
  [Resource.GRAPE]:      '🍇',
  [Resource.IRON]:       '⚙️', [Resource.IRON_ORE]:   '⛏️', [Resource.JAM]:        '🫙',
  [Resource.JEWELRY]:    '💍', [Resource.MELON]:      '🍉', [Resource.MILK]:       '🥛',
  [Resource.OIL]:        '🫗', [Resource.OLIVE]:      '🫒', [Resource.ONION]:      '🧅',
  [Resource.ORANGE]:     '🍊', [Resource.PANT]:       '👖', [Resource.PORK]:       '🥩',
  [Resource.POTATO]:     '🥔', [Resource.POTTERY]:    '🏺', [Resource.PUMPKIN]:    '🎃',
  [Resource.RICE]:       '🍚', [Resource.RUBBER]:     '🌴', [Resource.RUM]:        '🥃',
  [Resource.SALT]:       '🧂', [Resource.SAND]:       '🏜️', [Resource.SAUSAGE]:    '🌭',
  [Resource.SLATE]:      '🪨', [Resource.SOYBEAN]:    '🫘', [Resource.STATUE]:     '🗿',
  [Resource.STEEL]:      '⚒️', [Resource.STONE]:      '🪨', [Resource.SUGAR_CANE]: '🍬',
  [Resource.TIMBER]:     '🪵', [Resource.TOBACCO]:    '🌿', [Resource.TOMATO]:     '🍅',
  [Resource.TOOL]:       '🔧', [Resource.WAX]:        '🍯', [Resource.WHEAT]:      '🌾',
  [Resource.WINDOW]:     '🪟', [Resource.WINE]:       '🍷', [Resource.WOOD]:       '🪵',
  [Resource.WOOL]:       '🐑',
}

// PNG URL for a resource icon, or undefined to use the emoji fallback.
export function GetResourceIconSrc(type: Resource): string | undefined {
  const file = RESOURCE_ICON_FILES[type]
  return file ? `${RESOURCE_ICON_BASE}${file}` : undefined
}

export function GetResourceEmoji(type: Resource): string {
  return RESOURCE_EMOJI[type] ?? '📦'
}
