export enum Resident {
    FARMER = "Farmer",
    WORKER = "Worker",
    ARTISAN = "Artisan",
    SCHOLAR = "Scholar",
    ENTREPRENEUR = "Entrepreneur",
    MAGNATE = "Magnate",
}

export enum CityName {
    ANRELIA = "Anrelia",
    MINTAKA = "Mintaka",
    JINLIN = "Jinlin",
    COLUMBIA = "Columbia",
    SOLARA = "Solara",
}

export enum HouseType {
    COTTAGE = "Cottage",
    TENEMENT = "Tenament",
    HOUSE = "House",
    VILLA = "Villa",
    MANSION = "Mansion",
    ESTATE = "Estate",
}

export enum Resource {
    APPLE = "Apple",
    BANANA = "Banana",
    BERRY = "Berry",
    BOOT = "Boot",
    BRANDY = "Brandy",
    BREAD = "Bread",
    BRICK = "Brick",
    CABBAGE = "Cabbage",
    CANDLE = "Candle",
    CHEESE = "Cheese",
    CIDER = "Cider",
    CIGAR = "Cigar",
    CLAY = "Clay",
    COAL = "Coal",
    COCOA = "Cocoa",
    CONCRETE = "Concrete",
    CORN = "Corn",
    COTTON = "Cotton",
    EGG = "Egg",
    FEATHER_HAT = "Feather Hat",
    FISH = "Fish",
    FLOUR = "Flour",
    FUR = "Fur",
    GEM = "Gem",
    GLASS = "Glass",
    HORSE = "Horse",
    GOLD = "Gold",
    GRAPE = "Grape",
    CLAM = "Clam",
    IRON = "Iron",
    JAM = "Jam",
    MARBLE = "Marble",
    MELON = "Melon",
    MILK = "Milk",
    OIL = "Oil",
    OLIVE = "Olive",
    ORANGE = "Orange",
    ONION = "Onion",
    FURNITURE = "Furniture",
    JEWELRY = "Jewelry",
    IRON_ORE = "Iron Ore",
    GOLD_ORE = "Gold Ore",
    PANT = "Pant",
    TIMBER = "Timber",
    TOOL = "Tool",
    PORK = "Pork",
    POTATO = "Potato",
    POTTERY = "Pottery",
    PUMPKIN = "Pumpkin",
    SALT = "Salt",
    SAND = "Sand",
    SAUSAGE = "Sausage",
    SHIRT = "Shirt",
    SLATE = "Slate",
    SOYBEAN = "Soybean",
    STATUE = "Statue",
    STEEL = "Steel",
    STONE = "Stone",
    SUGAR_CANE = "Sugar Cane",
    RICE = "Rice",
    RUBBER= "Rubber",
    RUM = "Rum",
    TOBACCO = "Tobacco",
    TOMATO = "Tomato",
    WAX = "Wax",
    WEAPON = "Weapon",
    WHEAT = "Wheat",
    WINDOW = "Window",
    WINE = "Wine",
    WOOD = "Wood",
    WOOL = "Wool",
    // --- Jinlin (East Asian city) ---
    TEA = "Tea",
    SILK = "Silk",
    TOFU = "Tofu",
    PORCELAIN = "Porcelain",
    NOODLE = "Noodle",
    // --- Columbia (American frontier city) ---
    CORNBREAD = "Cornbread",
    BEEF = "Beef",
    LEATHER = "Leather",
    DENIM = "Denim",
    WHISKEY = "Whiskey",
    RAIL = "Rail",
    // --- Solara (African / tropical city) ---
    PALM_FRUIT = "Palm Fruit",
    PALM_OIL = "Palm Oil",
    COCOA_DRINK = "Cocoa Drink",
    COPPER = "Copper",
    BRONZE = "Bronze",
    INCENSE = "Incense",
    IVORY = "Ivory",
    // --- Mintaka (polar city) ---
    SMOKED_FISH = "Smoked Fish",
    FUR_COAT = "Fur Coat",
    REINDEER_MEAT = "Reindeer Meat",
    BLUBBER = "Blubber",
    WHALE_OIL = "Whale Oil",
    AMBER = "Amber",
}

export enum ServiceType {
    WATER = "Water",
    FIRE = "Fire",
    POLICE = "Policy",
    SCHOOL = "School",
    MARKET = "Market",
    TAVERN = "Tavern",
    CHURCH = "Church",
    HEALTH = "Health",
    JUSTICE = "Justice",
    ENGINEER = "Engineering",
}

export enum ProductionStatus {
    READY = "Ready",
    WAITING_DELIVERY = "Waiting Delivery",
    IN_PROGRESS = "In Progress",
    FINISHED = "Finished",
    WAITING_PICK_UP = "Waiting Pick Up"
}

export enum ShippingTaskType {
    READY = "Ready",
    PICKING_UP = "Picking Up",
    DELIVERYING = "Deliverying",
    RETURNING = "Returning",
}

export enum BuildingType {
    APPLE_ORCHARD = "Apple Orchard",
    BANANA_PLANTATION = "Banana Plantation",
    BERRY_GROVE = "Berry Grove",
    BRANDY_DISTILLERY = "Brandy Distillery",
    BAKERY = "Bakery",
    BRICKYARY = "Brickyard",
    CABBAGE_PATCH = "Lettuce Field",
    CANDLE_Manufactory = "Candle Manufactory",
    CREAMERY = "Creamery",
    CIDERY = "Cidery",
    CIGAR_FACTORY = "Cigar Factory",
    CLAY_PIT = "Clay Pit",
    COAL_KILN = "Coal Kiln",
    CONCRETE_PLANT = "Concrete Plant",
    SCULPTOR = "Sculptor",
    COCOA_PLANT = "Cocoa Plant",
    CORN_FIELD = "Corn Field",  
    COTTON_FIELD = "Cotton Field",
    CHICKEN_COOP = "Chicken Coop",
    FISHERY = "Fishery",
    HORSE_FARM = "Horse Farm",
    TRAPLINE = "Trapline",
    GEM_MINE = "Gem Mine",
    GLASSWORK = "Glassworks",
    GLAZIER = "Glazier",
    GOLD_MINE = "Gold Mine",
    VINEYARD = "Vineyard",
    WIND_MILL = "Wind Mill",
    PIG_FARM = "Pig Farm",
    LUMBER_HUT = "Lumber Hut",
    WHEAT_FARM = "Wheat Farm",
    IRON_MINE = "Iron Mine",
    CANNERY = "Preserve Shop",
    MELON_GARDEN = "Melon Garden",
    DIARY_FARM = "Dairy Farm",
    OLIVE_GROVE = "Olive Grove",
    ORANGE_ORCHARD = "Orange Orchard",
    ONION_FIELD = "Onion Field",
    PANT_SHOP = "Pant Shop",
    SHIRT_SHOP = "Shirt Shop",
    BOOT_SHOP = "Boot Shop",
    FORGE = "Forge",
    GOLDSMITH = "Goldsmith",
    TOOLSMITH = "Toolsmith",
    JEWELER = "Jeweler",
    CARPENTER_SHOP = "Carpenter Shop",
    WINERY = "Winery",
    OIL_PRESS = "Oil Press",
    RUM_DISTILLERY = "Rum Distillery",
    SAWMILL = "Sawmill",
    POTATO_FARM = "Potato Farm",
    POTTERY_SHOP = "Pottery Shop",
    PUMPKIN_PATCH = "Pumpkin Patch",
    SALTERN = "Saltern",
    SAND_PIT = "Sand Pit",
    BUTCHERY = "Butchery",
    MASON_SHOP = "Mason Shop",
    SOYBEAN_FARM = "Soybean Farm",
    STEELWORK = "Steelwork",
    STONE_QUARRY = "Stone Quarry",
    SUGAR_CANE_PLANTATION = "Sugar Cane Plantation",
    RICE_PADDY = "Rice Paddy",
    RUBBER_PLANTATION = "Rubber Plantation",
    TOBACCO_PLANTATION = "Tobacco Plantation",
    TOMATO_FIELD = "Tomato Field",
    APIARY = "Apiary",
    SHEEP_FARM = "Sheep Farm",
    HOUSE = "House",
    WELL = "Well",
    FIRE_STATION = "Fire Station",
    POLICE_STATION = "Police Station",
    SCHOOL = "School",
    MARKETPLACE = "Marketplace",
    TAVERN = "Tavern",
    CHAPEL = "Chapel",
    CLINIC = "Clinic",
    COURTHOUSE = "Courthouse",
    ENGINEER_STATION = "Engineer Station",
    WAREHOUSE = "Warehouse",
    SHIPYARD = "Shipyard",
    DOCK = "Dock",
    ROAD = "Road",
    DELETE = "Delete",
    // --- Jinlin (East Asian) buildings ---
    TEA_GARDEN = "Tea Garden",
    SILK_FARM = "Silk Farm",
    TOFU_SHOP = "Tofu Shop",
    KILN = "Kiln",
    NOODLE_SHOP = "Noodle Shop",
    // --- Columbia (American frontier) buildings ---
    CATTLE_RANCH = "Cattle Ranch",
    CORN_MILL = "Corn Mill",
    TANNERY = "Tannery",
    DENIM_MILL = "Denim Mill",
    WHISKEY_DISTILLERY = "Whiskey Distillery",
    RAIL_MILL = "Rail Mill",
    // --- Solara (African / tropical) buildings ---
    PALM_GROVE = "Palm Grove",
    PALM_OIL_PRESS = "Palm Oil Press",
    COCOA_SHOP = "Cocoa Shop",
    COPPER_MINE = "Copper Mine",
    BRONZE_FOUNDRY = "Bronze Foundry",
    INCENSE_GROVE = "Incense Grove",
    IVORY_CAMP = "Ivory Camp",
    // --- Mintaka (polar) buildings ---
    REINDEER_FARM = "Reindeer Farm",
    FUR_WORKSHOP = "Fur Workshop",
    SMOKEHOUSE = "Smokehouse",
    WHALING_POST = "Whaling Post",
    BLUBBER_PRESS = "Blubber Press",
    AMBER_MINE = "Amber Mine",
}

// "Land" is the general term for the buildable ground types (grass, dirt, sand);
// water is the non-buildable terrain. Trees and rocks are Features, not terrain.
export enum Terrain {
    GRASS = "Grass",
    SAND = "Sand",
    WATER = "Water",
}

// Natural features that sit on top of a land tile, like a building does: trees
// (for lumber / foraging) and rock outcrops (for mining). They coexist with the
// terrain underneath and are removable with the Delete tool.
export enum Feature {
    TREE = "Tree",
    ROCK = "Rock",
    BUSH = "Bush",
}

export enum ShipType {
    CARGO = "Cargo",
    CLIPPER = "Clipper",
    GRAND = "Grand"  
}