export enum Resident {
    FARMER = "Farmer",
    WORKER = "Worker",
    ARTISAN = "Artisan",
    SCHOLAR = "Scholar",
    ENTREPRENEUR = "Entrepreneur",
    MAGNATE = "Magnate",
}

export enum CityName {
    ANRELIA = "Anrelia",
    MINTAKA = "Mintaka",
    JINLIN = "Jinlin",
    DAKAR = "Dakar",
}

export enum HouseType {
    COTTAGE = "Cottage",
    TENEMENT = "Tenament",
    HOUSE = "House",
    VILLA = "Villa",
    MANSION = "Mansion",
    ESTATE = "Estate",
}

export enum Resource {
    APPLE = "Apple",
    BANANA = "Banana",
    BERRY = "Berry",
    BRANDY = "Brandy",
    BREAD = "Bread",
    BRICK = "Brick",
    CABBAGE = "Cabbage",
    CANDLE = "Candle",
    CHEESE = "Cheese",
    CIDER = "Cider",
    CIGAR = "Cigar",
    CLAY = "Clay",
    COAL = "Coal",
    COCOA = "Cocoa",
    CORN = "Corn",    
    COTTON = "Cotton",
    EGG = "Egg",
    FISH = "Fish",
    FLOUR = "Flour",
    FUR = "Fur",
    GEM = "Gem",
    GLASS = "Glass",
    GOLD = "Gold",
    GRAPE = "Grape",
    IRON = "Iron",
    JAM = "Jam",
    MELON = "Melon",
    MILK = "Milk",
    OLIVE = "Olive",
    ORANGE = "Orange",
    ONION = "Onion",
    OVERALL = "Overall",
    PLANK = "Plank",
    PORK = "Pork",
    POTATO = "Potato",
    POTTERY = "Pottery",
    PUMPKIN = "Pumpkin",
    SALT = "Salt",
    SAND = "Sand",
    SAUSAGE = "Sausage",
    SLATE = "Slate",
    SOYBEAN = "Soybean",
    STEEL = "Steel",
    STONE = "Stone",
    SUGAR_CANE = "Sugar Cane",
    RICE = "Rice",
    RUBBER= "Rubber",
    TOBACCO = "Tobacco",
    TOMATO = "Tomato",
    WAX = "Wax",
    WHEAT = "Wheat",
    WOOD = "Wood",
    WOOL = "Wool",
}

export enum ServiceType {
    WATER = "Water",
    FIRE = "Fire",
    POLICE = "Policy",
    SCHOOL = "School",
}

export enum ProductionStatus {
    READY = "Ready",
    WAITING_DELIVERY = "Waiting Delivery",
    IN_PROGRESS = "In Progress",
    FINISHED = "Finished",
    WAITING_PICK_UP = "Waiting Pick Up"
}

export enum ShippingTaskType {
    READY = "Ready",
    PICKING_UP = "Picking Up",
    DELIVERYING = "Deliverying",
    RETURNING = "Returning",
}

export enum BuildingType {
    APPLE_ORCHARD = "Apple Orchard",
    BANANA_PLANTATION = "Banana Plantation",
    BERRY_GROVE = "Berry Grove",
    BRANDY_DISTILLERY = "Brandy Distillery",
    BAKERY = "Bakery",
    BRICKYARY = "Brickyard",
    CABBAGE_PATCH = "Cabbage Patch",
    CANDLE_Manufactory = "Candle Manufactory",
    CREAMERY = "Creamery",
    CIDERY = "Cidery",
    CIGAR_FACTORY = "Cigar Factory",
    CLAY_PIT = "Clay Pit",
    COAL_KILN = "Coal Kiln",
    COCOA_PLANT = "Cocoa Plant",
    CORN_FIELD = "Corn Field",  
    COTTON_FIELD = "Cotton Field",
    CHICKEN_COOP = "Chicken Coop",
    FISHERY = "Fishery",
    TRAPLINE = "Trapline",
    GEM_MINE = "Gem Mine",
    GLASSWORK = "Glassworks",
    GOLD_MINE = "Gold Mine",
    VINEYARD = "Vineyard",
    WIND_MILL = "Wind Mill",
    PIG_FARM = "Pig Farm",
    LUMBER_HUT = "Lumber Hut",
    WHEAT_FARM = "Wheat Farm",
    IRON_MINE = "Iron Mine",
    CANNERY = "Cannery",
    MELON_GARDEN = "Melon Garden",
    DIARY_FARM = "Dairy Farm",
    OLIVE_GROVE = "Olive Grove",
    ORANGE_ORCHARD = "Orange Orchard",
    ONION_FIELD = "Onion Field",
    OVERALL_FACTORY = "Overall Factory",
    SAWMILL = "Sawmill",
    POTATO_FARM = "Potato Farm",
    POTTERY_SHOP = "Pottery Shop",
    PUMPKIN_PATCH = "Pumpkin Patch",
    SALTERN = "Saltern",
    SAND_PIT = "Sand Pit",
    BUTCHERY = "Butchery",
    MASON_SHOP = "Mason Shop",
    SOYBEAN_FARM = "Soybean Farm",
    STEELWORK = "Steelwork",
    STONE_QUARRY = "Stone Quarry",
    SUGAR_CANE_PLANTATION = "Sugar Cane Plantation",
    RICE_PADDY = "Rice Paddy",
    RUBBER_PLANTATION = "Rubber Plantation",
    TOBACCO_PLANTATION = "Tobacco Plantation",
    TOMATO_FIELD = "Tomato Field",
    APIARY = "Apiary",
    SHEEP_FARM = "Sheep Farm",
    HOUSE = "House",
    WELL = "Well",
    FIRE_STATION = "Fire Station",
    POLICE_STATION = "Police Station",
    SCHOOL = "School",
    WAREHOUSE = "Warehouse",
    SHIPYARD = "Shipyard",
    DOCK = "Dock",
    DELETE = "Delete",
}

export enum Terrain {
    LAND = "Land",
    GRASS = "Grass",
    FOREST = "Forest",
    SEA = "Sea",
    MOUNTAIN = "Mountain",
}

export enum ShipType {
    CARGO = "Cargo",
    CLIPPER = "Clipper",
    GRAND = "Grand"  
}